// tests/loadtest/s1_warm_cache.js
// Scenario 1 — Warm Cache Baseline
// Updated to load queries from corpus.json generated by gen-corpus.php

import http from 'k6/http';
import { check, sleep } from 'k6';
import { Rate, Trend } from 'k6/metrics';
import { SharedArray } from 'k6/data';

// ── Metrics ──────────────────────────────────────────────────────────────────
const errorRate   = new Rate('wcs_errors');
const dbHitTime   = new Trend('wcs_db_hit_duration', true);  // cold cache
const cacheHitTime= new Trend('wcs_cache_hit_duration', true); // warm cache

// ── Config ───────────────────────────────────────────────────────────────────
const BASE_URL = __ENV.WP_URL   || 'http://localhost:8081';
const NONCE    = __ENV.WP_NONCE || 'REPLACE_WITH_NONCE';

// ── Query corpus (generated by gen-corpus.php) ────────────────────────────────
// corpus.json is read once and shared across all VUs — zero extra memory per VU
const corpus = new SharedArray('queries', function () {
    const raw = open('./corpus.json');
    return JSON.parse(raw);
});

// ── Load shape ────────────────────────────────────────────────────────────────
export const options = {
    scenarios: {
        warm_ramp: {
            executor: 'ramping-vus',
            startVUs: 0,
            stages: [
                { duration: '30s',  target: 50  },  // ramp up
                { duration: '2m',   target: 100 },  // hold
                { duration: '60s',  target: 250 },  // increase
                { duration: '5m',   target: 250 },  // hold peak
                { duration: '30s',  target: 0   },  // ramp down
            ],
            gracefulRampDown: '10s',
        },
    },
    thresholds: {
        // Primary SLA
        http_req_duration:        ['p(50)<30', 'p(95)<100', 'p(99)<150'],
        http_req_failed:          ['rate<0.001'],
        wcs_errors:               ['rate<0.001'],
        // Warm-cache sub-latency (requests served from cache should be fast)
        wcs_cache_hit_duration:   ['p(99)<50'],
    },
};

// ── 30-second warm-up: populate cache before main load ───────────────────────
export function setup() {
    const warmupQueries = corpus.slice(0, 50); // seed top 50 queries
    warmupQueries.forEach(entry => {
        const url = `${BASE_URL}/wp-json/wcs/v1/search?q=${encodeURIComponent(entry.q)}&_wpnonce=${NONCE}`;
        http.get(url);
    });
    console.log('Cache warm-up complete — 50 queries pre-fetched.');
}

// ── Main VU function ──────────────────────────────────────────────────────────
export default function () {
    const fixedQuery = __ENV.FIXED_QUERY;
    const entry = corpus[Math.floor(Math.random() * corpus.length)];
    const queryStr = fixedQuery || entry.q;
    const queryType = fixedQuery ? 'fixed' : entry.type;
    const url   = `${BASE_URL}/wp-json/wcs/v1/search` +
                  `?q=${encodeURIComponent(queryStr)}&_wpnonce=${NONCE}`;

    const start = Date.now();
    const res   = http.get(url, {
        tags: { query_type: queryType, scenario: 's1_warm_cache' },
    });
    const dur = Date.now() - start;

    // Classify as cache hit (<= 40ms) or DB hit
    if (dur <= 40) {
        cacheHitTime.add(dur);
    } else {
        dbHitTime.add(dur);
    }

    const ok = check(res, {
        'HTTP 200':       (r) => r.status === 200,
        'valid JSON':     (r) => {
            try { JSON.parse(r.body); return true; }
            catch { return false; }
        },
        'is array':       (r) => {
            try { return Array.isArray(JSON.parse(r.body)); }
            catch { return false; }
        },
        '< 200ms':        (r) => r.timings.duration < 200,
    });

    errorRate.add(!ok);

    // Think time — simulates realistic user pacing
    sleep(Math.random() * 0.4 + 0.1); // 100–500ms
}

// ── Teardown: print Redis key count ──────────────────────────────────────────
export function teardown(data) {
    console.log('S1 complete. Run: redis-cli --scan --pattern "*wcs_v*" | wc -l');
    console.log('to verify cache key count matches expectations.');
}
